# permissions for end users to edit pds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: pd-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: multi-controller
    app.kubernetes.io/part-of: multi-controller
    app.kubernetes.io/managed-by: kustomize
  name: pd-editor-role
rules:
- apiGroups:
  - tidb-cluster.dbaas
  resources:
  - pds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tidb-cluster.dbaas
  resources:
  - pds/status
  verbs:
  - get
