# permissions for end users to view tikvs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: tikv-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: multi-controller
    app.kubernetes.io/part-of: multi-controller
    app.kubernetes.io/managed-by: kustomize
  name: tikv-viewer-role
rules:
- apiGroups:
  - tidb-cluster.dbaas
  resources:
  - tikvs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tidb-cluster.dbaas
  resources:
  - tikvs/status
  verbs:
  - get
