apiVersion: tidb-cluster.dbaas/v1
kind: Tidb
metadata:
  labels:
    app.kubernetes.io/name: tidb
    app.kubernetes.io/instance: tidb-sample
    app.kubernetes.io/part-of: multi-controller
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: multi-controller
  name: tidb-sample
spec:
  # TODO(user): Add fields here
