apiVersion: v1
kind: PersistentVolume
metadata:
  name: tikv-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/sujingyu/mnt/tikv-volume"