---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - dbaas.cs528
  resources:
  - tidbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dbaas.cs528
  resources:
  - tidbs/finalizers
  verbs:
  - update
- apiGroups:
  - dbaas.cs528
  resources:
  - tidbs/status
  verbs:
  - get
  - patch
  - update
