---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - tidbop.cs528
  resources:
  - tidbops
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tidbop.cs528
  resources:
  - tidbops/finalizers
  verbs:
  - update
- apiGroups:
  - tidbop.cs528
  resources:
  - tidbops/status
  verbs:
  - get
  - patch
  - update
