# permissions for end users to view tidbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: tidb-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: tidbop
    app.kubernetes.io/part-of: tidbop
    app.kubernetes.io/managed-by: kustomize
  name: tidb-viewer-role
rules:
- apiGroups:
  - dbaas.cs528
  resources:
  - tidbs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dbaas.cs528
  resources:
  - tidbs/status
  verbs:
  - get
