apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: pd
  name: pd
spec:
  ports:
  - port: 2379
    protocol: TCP
    targetPort: 2379
    name: port1
  - port: 2380
    protocol: TCP
    targetPort: 2380
    name: port2
  selector:
    app: pd
status:
  loadBalancer: {}
