---
apiVersion: v1
kind: Pod
metadata:
  name: basic-tikv-0
  labels:
    component: tikv
  namespace: tidb-cluster
spec:
  containers:
  - name: basic-tikv-0
    image: pingcap/tikv:latest
    ports:
      - containerPort: 20160
    args:
      - "--pd=http://basic-pd:2379"
      - "--addr=0.0.0.0:20160"
      - "--advertise-addr=basic-tikv-peer.tidb-cluster.svc.cluster.local:20160"

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    pingcap.com/last-applied-configuration: '{"ports":[{"name":"peer","protocol":"TCP","port":20160,"targetPort":20160}],"selector":{"app.kubernetes.io/component":"tikv","app.kubernetes.io/instance":"basic","app.kubernetes.io/managed-by":"tidb-operator","app.kubernetes.io/name":"tidb-cluster"},"clusterIP":"None","publishNotReadyAddresses":true}'
  labels:
    component: tikv
  name: basic-tikv-peer
  namespace: tidb-cluster
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: peer
    port: 20160
    protocol: TCP
    targetPort: 20160
  publishNotReadyAddresses: true
  selector:
    component: tikv
  sessionAffinity: None
  type: ClusterIP

