apiVersion: v1
kind: Pod
metadata:
  labels:
    app: tikv
  name: tikv
spec:
    containers:
    - command:
      - /tikv-server
      - --pd=pd:2379
      image: pingcap/tikv
      name: tikv
      ports:
      - containerPort: 20160
      resources: {}
    
status: {}
