apiVersion: v1
kind: Pod
metadata:
  labels:
    app: pd
  name: pd
spec:
    containers:
    - image: pingcap/pd
      name: pd
      args:
        - --client-urls=http://0.0.0.0:2379
        - --advertise-client-urls=http://$(MY_POD_IP):2379
        - --peer-urls=http://0.0.0.0:2380
        - --advertise-peer-urls=http://$(MY_POD_IP):2380
      ports:
        - containerPort: 2379
        - containerPort: 2380
      resources: {}
      env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pd
  name: pd-svc
spec:
  ports:
  - port: 2379
    protocol: TCP
    targetPort: 2379
    name: port1
  - port: 2380
    protocol: TCP
    targetPort: 2380
    name: port2
  selector:
    app: pd
