apiVersion: v1
kind: Pod
metadata:
  labels:
    app: tikv
  name: tikv
spec:
    containers:
    - command:
        - /tikv-server
        #- --pd=pd-svc:2379
      image: pingcap/tikv
      args:
        - "--pd=pd-svc:2379"
      name: tikv
      ports:
        - containerPort: 20160
      resources: {}
